"""Adiciona campos PagSeguro

Revision ID: b972ca806c16
Revises: 0711e8d7b90d
Create Date: 2026-02-14 23:01:59.147012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b972ca806c16'
down_revision = '0711e8d7b90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pg_payment_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pg_payment_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('pg_payment_link')
        batch_op.drop_column('pg_payment_code')

    # ### end Alembic commands ###
